name: Publish Image

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  id-token: write
  contents: write

jobs:
  build_per_arch:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Architecture-Specific Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          sbom: false
          tags: ghcr.io/${{ github.repository }}:${{ matrix.arch }}

  create_manifest:
    name: Create and Push Docker Manifest
    runs-on: ubuntu-latest
    needs: build_per_arch
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Manifest List
        env:
          REPO: ghcr.io/${{ github.repository }}
        run: |
          IMG_AMD64="${REPO}:amd64"
          IMG_ARM64="${REPO}:arm64"

          echo "Creating manifest for ${REPO}:latest pointing to:"
          echo "  ${IMG_AMD64}"
          echo "  ${IMG_ARM64}"
          
          docker manifest create --amend "${REPO}:latest" \
            "${IMG_AMD64}" \
            "${IMG_ARM64}"
          
          # Annotate (optional but good practice, especially if images lack proper arch metadata)
          docker manifest annotate "${REPO}:latest" "${IMG_AMD64}" --os linux --arch amd64
          docker manifest annotate "${REPO}:latest" "${IMG_ARM64}" --os linux --arch arm64
          
          docker manifest push "${REPO}:latest"

          echo "Creating manifest for ${REPO} pointing to:"
          echo "  ${IMG_AMD64}"
          echo "  ${IMG_ARM64}"

          docker manifest create --amend "${REPO}" \
            "${IMG_AMD64}" \
            "${IMG_ARM64}"

          # Annotate (optional but good practice)
          docker manifest annotate "${REPO}" "${IMG_AMD64}" --os linux --arch amd64
          docker manifest annotate "${REPO}" "${IMG_ARM64}" --os linux --arch arm64

          docker manifest push "${REPO}"
